package util;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import controlador.Configuer;
import java.net.URL;
import java.util.MissingResourceException;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 * Interface icons: the SVG of the icon theme (imagens/svg/, generated by
 * dev/icones/gerar_svg.py) when there is one, else the original bitmap.
 *
 * The SVGs are drawn in FlatLaf's action colors, so FlatSVGIcon recolors them for light and
 * dark themes by itself, and they stay sharp at any scale. Icons painted on white diagram
 * paper use noPapel instead, with the same sources and no theme filter or UI font scaling.
 */
public final class Icones {

    private static final String PASTA_SVG = "imagens/svg/";

    private Icones() {
    }

    /**
     * Icon for a bitmap resource path as written by the form designer ("/imagens/x.png"),
     * shown at 16px.
     */
    public static Icon de(String recurso) {
        Icon svg = svg(nomeBase(recurso), 16);
        if (svg instanceof FlatSVGIcon icon && icon.getColorFilter() == null) {
            return new IconeEmCache(icon); // fixed-color icons: render the vector once
        }
        if (svg != null) {
            return svg; // icons with a state-dependent color filter repaint from the vector
        }
        URL url = Icones.class.getResource(recurso);
        return url == null ? null : new ImageIcon(url);
    }

    /**
     * SVG icon for an image key of principal/Propriedades (as Configuer resolves it), or null
     * when the key has no SVG yet; callers then keep the bitmap they already load.
     */
    public static Icon daChave(String chave, int tamanho) {
        Icon icon = vetorDaChave(chave, tamanho);
        return icon instanceof FlatSVGIcon svg && svg.getColorFilter() == null ? new IconeEmCache(svg) : icon;
    }

    /** The SVG itself (an ImageIcon), for callers that need its Image rather than a painter. */
    public static Icon vetorDaChave(String chave, int tamanho) {
        try {
            return svg(nomeBase(Configuer.getResourceMap().getString(chave)), tamanho);
        } catch (MissingResourceException e) {
            return null;
        }
    }

    /** Fixed paper colors and document units; the caller's Graphics2D supplies zoom/HiDPI. */
    public static Icon noPapel(String chave, int tamanho) {
        return IconeNoPapel.de(baseDaChave(chave), tamanho, null);
    }

    /** Disabled table markers retain the document's chosen foreground, without rasterizing. */
    public static void pinteNoPapel(String chave, java.awt.Graphics2D g, int x, int y,
            int tamanho, java.awt.Color tinta) {
        Icon icon = IconeNoPapel.de(baseDaChave(chave), tamanho, tinta);
        if (icon != null) icon.paintIcon(null, g, x, y);
    }

    private static String baseDaChave(String chave) {
        try {
            return fonte(nomeBase(Configuer.getResourceMap().getString(chave)));
        } catch (MissingResourceException e) {
            return null;
        }
    }

    // Constraints and IR editors share the palette sources, including the FK composite.
    private static String fonte(String base) {
        return switch (base) {
            case "ir_pk" -> "CampoK";
            case "ir_fk" -> "CampoKFK";
            default -> base;
        };
    }

    private static Icon svg(String base, int tamanho) {
        base = fonte(base);
        String caminho = PASTA_SVG + base + ".svg";
        if (Icones.class.getClassLoader().getResource(caminho) == null) {
            return null;
        }
        FlatSVGIcon icon = new FlatSVGIcon(caminho, tamanho, tamanho);
        if (base.equals("log_erro")) icon.setColorFilter(new FlatSVGIcon.ColorFilter((component, color) ->
                MensagensStatus.corErro()));
        if (base.equals("trash-2")) icon.setColorFilter(new FlatSVGIcon.ColorFilter((component, color) ->
                component instanceof javax.swing.AbstractButton button && button.getModel().isRollover()
                        ? MensagensStatus.corErro() : EstiloUI.cor("Label.foreground")));
        return icon;
    }

    /** "/imagens/menu_salvar.png" -> "menu_salvar". */
    private static String nomeBase(String arquivo) {
        String nome = arquivo.substring(arquivo.lastIndexOf('/') + 1).trim();
        int ponto = nome.lastIndexOf('.');
        return ponto > 0 ? nome.substring(0, ponto) : nome;
    }
}
